export const GET_ORDER = "GET_ORDER"
export const GET_USER = "GET_USER"
export const GET_ORDENID = "GET_ORDENID"
export const POST_USER = "POST_USER"
export const PUT_USER = "PUT_USER"
export const DELETE_USER = "DELETE_USER"